"""Camp's own constants: the documents Brain Waves reads, and what a new week starts with.

The two spreadsheet ids are not secrets — reading either still needs Drive permission — so
they live here rather than being built in, which means Brain Waves works out of the box and
a config file only has to say what camp wants changed.


The location list is camp's, taken from the BACKEND tab of the old workbook. Editing the
Locations tab of a week sheet changes that week; editing this list changes every week made
from now on.
"""

SKILLS_SHEET = "1Woqx_vthAAbGh-CSGFwgMDooqhkt0PWV1XKLiNqiJvU"
CATEGORIES_SHEET = "1ldemXKtda6NgmCYp6vDQXVSvO6bdIRiMieNr400A6Ug"

DEFAULT_LOCATIONS = (
    "_Other",
    "Aerial Silks",
    "Aerial Bungee",
    "Agility Course",
    "Amphitheatre",
    "Archery",
    "Archery Treehouse",
    "Back 40 1",
    "Back 40 2",
    "Back 40 3",
    "Blockprinting",
    "Campfire Circle",
    "Canopy Tour",
    "Cedar",
    "Ceramics",
    "Climbing Wall",
    "Craft Shack 1",
    "Craft Shack 2",
    "Dining Area 1",
    "Dining Area 2",
    "Dirt Bowl",
    "Field - Cedar",
    "Field - Climbing Wall",
    "Field - Giant's Junkyard",
    "Field - Lake",
    "Field - Tiny",
    "Flowspace",
    "Gaga Ball",
    "Giant Swing",
    "Gravity Zip",
    "Hammock Village",
    "Horses",
    "Hot Rocks",
    "Hot Tub",
    "Kitchen",
    "Lake - Mats",
    "Lake - Outer 1",
    "Lake - Outer 2",
    "Lake - Swim Area 1",
    "Lake - Swim Area 2",
    "Lake - Swing",
    "Lake - Trampoline",
    "Leap of Faith",
    "Lodge",
    "Low Ropes 1",
    "Low Ropes 2",
    "Low Ropes 3",
    "Low Ropes RH 1",
    "Low Ropes RH 2",
    "Low Ropes RH 3",
    "Madrone Cradle",
    "Manzi",
    "Oak",
    "Oak Swing",
    "Offsite 1",
    "Offsite 2",
    "Offsite 3",
    "Old School Play Yard",
    "Outdoor Kitchen",
    "PANDA",
    "Parking Lot",
    "Pine",
    "Pine Hill",
    "Pine Keep",
    "Riflery",
    "Secret Pool",
    "Slip n' Slide",
    "Tea Pagoda",
    "The Falls - Bottom",
    "The Falls - Top",
    "Throwing Range",
    "Tree Climbing",
    "Wandering",
)

DEFAULT_CABINS = (
    "M1",
    "M2",
    "M3",
    "M4",
    "M5",
    "P1",
    "P2",
    "P3",
    "P4",
    "P5",
    "P6",
    "O1",
    "O2",
    "O3",
    "O4",
    "O5",
    "C1",
    "C2",
    "C3",
    "C4",
    "C5",
)
